name: Generate PDF

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  convert_via_pandoc:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Get all changed markdown files
        id: changed-markdown-files
        uses: tj-actions/changed-files@22103cc46bda19c2b464ffe86db46df6922fd323 # v47.0.5
        with:
          # Avoid using single or double quotes for multiline patterns
          files: |
            **.md

      - name: List all changed files markdown files
        id: files_list
        if: steps.changed-markdown-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-markdown-files.outputs.all_changed_files }}
        uses: docker://pandoc/latex:3.8
        with:
          args: -f markdown+rebase_relative_paths --output=output/proposal.pdf ${{ steps.changed-markdown-files.outputs.all_changed_files }}

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        id: upload
        with:
          name: proposal
          path: output/proposal.pdf
          if-no-files-found: error
          archive: false
